### ISSUE TITLE
BadAuthentication with app-password

### ISSUE THREAD

**Issue by michaelblight** [aFrankLion/hass-google_keep#20]
I assume this is still working for some people, but I'm getting an authentication error. I've tried an app specific password as mentioned in [this issue](https://github.com/aFrankLion/hass-google_keep/issues/15) but that is giving me the error below:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 286, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/gkeep/__init__.py", line 71, in setup
    login_success = keep.login(username, password)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gkeepapi/__init__.py", line 695, in login
    ret = auth.login(username, password, device_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gkeepapi/__init__.py", line 59, in login
    raise exception.LoginException(
gkeepapi.exception.LoginException: ('BadAuthentication', None)
```
I'm using HAOS 2023.6.2 and my google account has two-factor authentication.

**Comment by konradjonsson** [comment]
I'm experiencing this issue as well. Using 2023.8.3.

**Comment by HappyGitCake** [comment]
same here:

```
Logger: homeassistant.setup
Source: custom_components/gkeep/__init__.py:71
Integration: gkeep (documentation)
First occurred: 17:05:39 (1 occurrences)
Last logged: 17:05:39

Error during setup of component gkeep
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 288, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/gkeep/__init__.py", line 71, in setup
    login_success = keep.login(username, password)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gkeepapi/__init__.py", line 695, in login
    ret = auth.login(username, password, device_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gkeepapi/__init__.py", line 59, in login
    raise exception.LoginException(
gkeepapi.exception.LoginException: ('BadAuthentication', None)
```

this happens with or without 2FA

**Comment by teadragon7** [comment]
Same here

**Comment by StefanoGiu** [comment]
I used keyring and tokens to make it work again. How can I create a pull request?
