### ISSUE TITLE
Error while setting up google_keep platform for sensor

### ISSUE THREAD

**Issue by austwhite** [aFrankLion/hass-google_keep#4]
When setting up this integration in Home Assistant, I get this error in the LOG file.
`"Error while setting up google_keep platform for sensor"`
I have also noticed no lists are showing in Home Assistant any longer.
I am using version 1.0.0 of the  Hass-google_keep installed from HACS.
I am using Home Assistant version 0.109.6.
This was last known to work in 0.107.5.
I have tried recreating the Google App password, as per install instructions, but this has not solved the issue.
Please advise if anything additional is needed to investigate this issue.

**Full log and Traceback:**
```
Log Details (ERROR)
Logger: homeassistant.components.sensor
Source: custom_components/google_keep/sensor.py:39
Integration: Sensor (documentation, issues)
First occurred: 6:35:33 PM (1 occurrences)
Last logged: 6:35:33 PM

Error while setting up google_keep platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/google_keep/sensor.py", line 39, in setup_platform
    login_success = keep.login(username, password)
  File "/usr/local/lib/python3.7/site-packages/gkeepapi/__init__.py", line 695, in login
    self.load(auth, state, sync)
  File "/usr/local/lib/python3.7/site-packages/gkeepapi/__init__.py", line 741, in load
    self.sync(True)
  File "/usr/local/lib/python3.7/site-packages/gkeepapi/__init__.py", line 1019, in sync
    labels=[i.save() for i in self._labels.values()] if labels_updated else None,
  File "/usr/local/lib/python3.7/site-packages/gkeepapi/__init__.py", line 359, in changes
    json=params
  File "/usr/local/lib/python3.7/site-packages/gkeepapi/__init__.py", line 221, in send
    response = self._send(**req_kwargs).json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by austwhite** [comment]
Ignore this.
Wrong repo lol.
Sorry
