### ISSUE TITLE
Error during setup of component google_keep

### ISSUE THREAD

**Issue by coolguymatt** [aFrankLion/hass-google_keep#6]
I believe this started in 0.109

```
Log Details (ERROR)
Logger: homeassistant.setup
Source: custom_components/google_keep/__init__.py:69
First occurred: 9:06:13 AM (1 occurrences)
Last logged: 9:06:13 AM

Error during setup of component google_keep
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 171, in _async_setup_component
    hass, processed_config
  File "/usr/local/lib/python3.7/asyncio/coroutines.py", line 120, in coro
    res = func(*args, **kw)
  File "/config/custom_components/google_keep/__init__.py", line 69, in async_setup
    login_success = keep.login(username, password)
  File "/usr/local/lib/python3.7/site-packages/gkeepapi/__init__.py", line 519, in login
    self.load(auth, state, sync)
  File "/usr/local/lib/python3.7/site-packages/gkeepapi/__init__.py", line 565, in load
    self.sync(True)
  File "/usr/local/lib/python3.7/site-packages/gkeepapi/__init__.py", line 825, in sync
    labels=[i.save() for i in self._labels.values()] if labels_updated else None,
  File "/usr/local/lib/python3.7/site-packages/gkeepapi/__init__.py", line 331, in changes
    json=params
  File "/usr/local/lib/python3.7/site-packages/gkeepapi/__init__.py", line 205, in send
    response = self._send(**req_kwargs).json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by aFrankLion** [comment]
I noticed the same issue in my setup recently. Looks like the issue has been resolved by using gkeepapi version 0.11.14. I'll update the manifest. Let me know if this resolves the issue for you, @coolguymatt .

**Comment by coolguymatt** [comment]
Yes this fixed it

**Comment by coolguymatt** [comment]
I updated and then could not update HA to 0.110.4. Removing the custom component allowed me to continue.
