### ISSUE TITLE
broken in HA 0.118

### ISSUE THREAD

**Issue by maximunited** [aFrankLion/hass-google_keep#7]
```
Logger: homeassistant.setup
Source: custom_components/google_keep/__init__.py:67
First occurred: 5:00:47 PM (1 occurrences)
Last logged: 5:00:47 PM

Error during setup of component google_keep
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/google_keep/__init__.py", line 67, in setup
    login_success = keep.login(username, password)
  File "/usr/local/lib/python3.8/site-packages/gkeepapi/__init__.py", line 693, in login
    ret = auth.login(username, password, get_mac())
  File "/usr/local/lib/python3.8/site-packages/gkeepapi/__init__.py", line 59, in login
    raise exception.LoginException(
gkeepapi.exception.LoginException: ('BadAuthentication', None)
```

**Comment by maximunited** [comment]
Seems to be caused by issue [#81](https://github.com/kiwiz/gkeepapi/issues/81) in gkeepapi

**Comment by aFrankLion** [comment]
This seems to have been resolved now in the issue you linked. Closing this, but let me know if the issue persists.
